name: Deploy Linux GUI to Fly.io

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Fly.io CLI manually
        run: |
          curl -L https://fly.io/install.sh | sh
          echo "$HOME/.fly/bin" >> $GITHUB_PATH

      - name: Deploy to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          fly apps list | grep robfly || fly apps create robfly --org personal
          fly volumes create robby_data --region lax --size 30 --app robfly || true
          fly deploy --remote-only
      
      - name: Tambah IPv4 Publik
        run: |
          fly ips allocate-v4 --app robfly --yes || echo "IPv4 sudah ada atau gagal allocate"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
